== OpenShift S2I Builder for Java (OpenJDK/OracleJDK)
This Source-to-Image Builder let's you create projects targetting Java OpenJDK 8 and/or OracleJDK 8, based on
https://access.redhat.com/containers/#/registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift[Red Hat's OpenJDK Image for Java Applications]

It's just a baseline for those of you which need to create your own Java S2I image and want to begin from Red Hat's supported images.

== Build in OpenShift
* First load all the needed resources in a project.

----
oc apply -f https://raw.githubusercontent.com/soukron/s2i-java-openshift/openshift/resources/s2i-java-openshift.json
----

* Once the builder **s2i-openjdk18-openshift** and/or **s2i-oraclejdk8-openshift** have been registered, you can create an app by using the builder images using a regular Git repository.

== Samples
Run __undertow__ sample application using new custom OpenJDK S2I image:
----
oc new-app --name undertow \
           --context-dir undertow-servlet \
           --image-stream=s2i-openjdk18-openshift \
           https://github.com/jboss-openshift/openshift-quickstarts 
----

Run __undertow__ sample application using new custom OracleJDK S2I image:
----
oc new-app --name undertow \
           --context-dir undertow-servlet \
           --image-stream=s2i-oraclejdk8-openshift \
           https://github.com/jboss-openshift/openshift-quickstarts 
----

== Disclaimers
* In order to build this images you need a valid Red Hat subscription entitlement to access the repositories and install software.
* Don't forget also https://www.redhat.com/en/about/eula/oracle-java-se[Oracle's license agreement] or devil will come to you.
